sonar.projectKey=GDipSA-Team-5_AD-Project---ML
sonar.organization=gdipsa-team-5

sonar.sources=.
sonar.tests=tests

sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml

# Exclusions - exclude notebooks, data, cache, and model files
sonar.exclusions=**/Notebooks/**,**/Cleaned-data/**,**/__pycache__/**,**/*.pkl,**/*.joblib,**/venv/**,**/data/**,**/.ipynb_checkpoints/**

